AlliedRenewableEnergyLTD/Backup/AlliedRenewableEnergyLTD/Controllers/AboutUsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AlliedRenewableEnergyLTD.Controllers
{
    public class AboutUsController : Controller
    {
        //
        // GET: /About/

        public ActionResult Index()
        {
            return View();
        }

    }
}

AlliedRenewableEnergyLTD/Backup/AlliedRenewableEnergyLTD/Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Net;
using System.Net.Mail;

namespace AlliedRenewableEnergyLTD.Controllers
{
    public class ContactController : Controller
    {
        //
        // GET: /Contact/

        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Index(string name, string email, string phone, string message)
        {
            try
            {
                //Create the msg object to be sent
                MailMessage msg = new MailMessage();
                //Add your email address to the recipients
                msg.To.Add("sales@myalliedbd.com");
                //Configure the address we are sending the mail from
                MailAddress address = new MailAddress("website@myalliedbd.com");
                msg.From = address;
                msg.Subject = "Website Feedback";
                string body = "From: " + name + "\n";
                body += "Email: " + email + "\n";
                body += "phone: " + phone + "\n\n";
                body += message + "\n";
                msg.Body = body;

                SmtpClient client = new SmtpClient();
                client.Host = "relay-hosting.secureserver.net";
                client.Port = 25;
                //Send the msg
                client.Send(msg);

                ViewBag.msg = "Mail Sent. Thank You For Contacting Us.";
                return View();
            }
            catch(Exception)
            {
                ViewBag.msg = "Something Is Wrong. Try Again.";
                return View();
            }
        }
    }
}

AlliedRenewableEnergyLTD/Backup/AlliedRenewableEnergyLTD/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AlliedRenewableEnergyLTD.Models;

namespace AlliedRenewableEnergyLTD.Controllers
{
    public class LoginController : Controller
    {
        //
        // GET: /Login/

        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Index(string UsernameTB, string PasswordTB)
        {
            if (UsernameTB != null || PasswordTB != null)
            {
                string username = UsernameTB;
                string password = PasswordTB;
                AlliedEntities db = new AlliedEntities();
                var q = (from p in db.LoginInfos
                         where p.username.Equals(username) && p.password.Equals(password)
                         select p);
                if (q.Count() == 1)
                {
                    Session["user"] = q.FirstOrDefault().username.ToString();
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    @ViewBag.msg = "Incorrect Username/Password";
                    return View();
                }
            }
            else
            {
                @ViewBag.msg = "Incorrect Username/Password";
                return View();
            }
        }
        public ActionResult Logout()
        {
            Session["user"] = null;
            return RedirectToAction("Index", "Home");
        }
    }
}

AlliedRenewableEnergyLTD/Backup/AlliedRenewableEnergyLTD/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AlliedRenewableEnergyLTD.Models;

namespace AlliedRenewableEnergyLTD.Controllers
{
    public class ProductsController : Controller
    {
        //
        // GET: /Products/

        public ActionResult Index(string category, string search)
        {
            using(AlliedEntities db = new AlliedEntities())
            {
                if (search != null)
                {
                    ViewBag.Title = "Allied - " + search;
                    var q = from p in db.Products
                            where p.title.Contains(search)
                            orderby p.id descending
                            select p;
                    return View("Index", q.ToList());
                }
                if (category != null)
                {
                    string Category = category;
                    ViewBag.Title = "Allied - " + category;

                    var m = from p in db.Products
                            where p.category.Equals(Category)
                            orderby p.id descending
                            select p;
                    return View(m.ToList());
                }
                else
                {
                    ViewBag.Title = "Allied - Products";

                    var m = from p in db.Products
                            orderby p.id descending
                            select p;
                    return View(m.ToList());
                }

            }
        }
        public FileContentResult GetImage(int id)
        {
            AlliedEntities db = new AlliedEntities();
            var q = from p in db.Products
                    where p.id == id
                    select p;
            byte[] byteArray = q.FirstOrDefault().imagebytes;
            if (byteArray != null)
            {
                return new FileContentResult(byteArray, q.FirstOrDefault().imagetype);
            }
            else
            {
                return null;
            }
        }

    }

}

AlliedRenewableEnergyLTD/Backup/AlliedRenewableEnergyLTD/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Allied LED lights are a smart innovation in the future of lighting. Since the beginning our portfolio has grown continuously in size and scope. Advanced technology, energy efficiency and durability put Allied LED lights years ahead, giving it a clear edge in today’s market. Allied LED products are crafted to meet global standards like CE, TUV, ROHS and KC. Our lights are superior quality lights products, priced fairly, and can meet your desired expectations." />
	<title>@ViewBag.Title</title>
    <link rel="icon" href="@Url.Content("~/content/img/favicon.png")"/>
	<link rel="stylesheet" href="~/Content/css/font-awesome.min.css"/>
	<link rel="stylesheet" href="~/Content/css/bootstrap.min.css"/>
	<link rel="stylesheet" href="~/Content/css/default.css"/>
    <link rel="stylesheet" href="~/Content/css/mainmap.css"/>
    <link href="~/Content/css/titles.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/css/project.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/css/mystyle.css" rel="stylesheet" type="text/css" />
    
    <link href='http://fonts.googleapis.com/css?family=Economica:400,700' rel='stylesheet' type='text/css'>
	<link href='http://fonts.googleapis.com/css?family=Open+Sans:600italic,400,800,700,300' rel='stylesheet' type='text/css' />

	<!-- Start WOWSlider.com HEAD section --> <!-- add to the <head> of your page -->
	<link rel="stylesheet" type="text/css" href="~/Content/engine1/style.css" />
	<script type="text/javascript" src="~/Content/engine1/jquery.js"></script>
	

</head>

<body>

	<!-- ====================================================
	header section -->
	<header class="top-header">
        <div class="top-bar">
            <div class="container">
                <div class="row">
                    
                    <div class="col-sm-12 col-xs-12">
                       <div class="social">
                            <ul class="social-share">
                                <li><a style="background:#00aced" onmouseover="this.style.backgroundColor='#c52d2f'" onmouseout="this.style.backgroundColor='#00aced'" href="#"><i class="fa fa-twitter"></i></a></li>
                                <li><a style="background:#3b5998" onmouseover="this.style.backgroundColor='#c52d2f'" onmouseout="this.style.backgroundColor='#3b5998'" href="https://www.facebook.com/pages/Allied-LED-Be-smart-Power-smart/807392392678655?fref=ts" target="_blank"><i class="fa fa-facebook"></i></a></li>
                                <li><a style="background:#12A5F4" onmouseover="this.style.backgroundColor='#c52d2f'" onmouseout="this.style.backgroundColor='#12A5F4'" href="#"><i class="fa fa-skype"></i></a></li>
                            </ul>
                            <div class="search">
                                @using (Html.BeginForm("Index", "Products",FormMethod.Get))
                                {
                                    <input type="text" name="search" class="search-form" autocomplete="off" placeholder="Search Products">
                                    <i class="fa fa-search" style="color:#212121"></i>
                                }
                           </div>
                           <ul class="social-share">
                                @if (Session["user"] == null)
                                {
                                <li class="divider"></li>
                                <li class="divider"></li>
                                <li class="divider"></li>
                                
                                <li><a href="@Url.Action("Index", "Login")" style="background:#c52d2f" onmouseover="this.style.backgroundColor='#42b3e5'" onmouseout="this.style.backgroundColor='#c52d2f'">
                                        <i class="fa fa-user"></i>
                                    </a>
                                </li>
                                }
                                else
                                {
                                <li class="divider"></li>
                                <li class="divider"></li>
                                <li class="divider"></li>
                                <li><a href="@Url.Action("Index", "Manage")" style="background:#c52d2f" onmouseover="this.style.backgroundColor='#42b3e5'" onmouseout="this.style.backgroundColor='#c52d2f'">
                                    <i class="fa fa-cogs"></i>
                                </a>
                                </li>
                                <li><a href="@Url.Action("Index", "AddProducts")" style="background:#c52d2f" onmouseover="this.style.backgroundColor='#42b3e5'" onmouseout="this.style.backgroundColor='#c52d2f'">
                                    <i class="fa fa-th-large"></i>
                                </a>
                                </li>
                                <li><a href="@Url.Action("Logout", "Login")" style="background:#c52d2f" onmouseover="this.style.backgroundColor='#42b3e5'" onmouseout="this.style.backgroundColor='#c52d2f'">
                                    <i class="fa fa fa-times"></i>
                                </a>
                                </li>
                                }
                            </ul>
                       </div>
                    </div>
                </div>
            </div><!--/.container-->
        </div><!--/.top-bar-->
		<div class="container">
			<div class="row">
				<div class="col-md-2 col-xs-4 col-sm-2 header-logo" style="padding-top:29px">
					<a href="@Url.Action("Index", "Home")"><img src="~/Content/img/logo.png" alt="" class="img-responsive logo"></a>
				</div>

				<div class="col-md-10 col-xs-8 col-sm-10">
					<nav class="navbar navbar-default">
					  <div class="container-fluid nav-bar">
					    <!-- Brand and toggle get grouped for better mobile display -->
					    <div class="navbar-header">
					      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
					        <span class="sr-only">Toggle navigation</span>
					        <span class="icon-bar"></span>
					        <span class="icon-bar"></span>
					        <span class="icon-bar"></span>
					      </button>
					    </div>

					    <!-- Collect the nav links, forms, and other content for toggling -->
					    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
					      
					      <ul class="nav navbar-nav navbar-right">
					        <li><a class="menu @ViewBag.Active1" href="@Url.Action("Index", "Home")" >Home</a></li>
                            <li><a class="menu @ViewBag.Active7" href="@Url.Action("Index", "AboutUs")" >About Us</a></li>
					        <li>
                                <a class="menu" href="" class="dropdown-toggle" data-hover="dropdown" data-toggle="dropdown">Home & Offices <b class="caret"></b></a>
                                <ul class="dropdown-menu" id="border">
                                    <li class="dropdown">
                                        <div class="row" style="width: 500px;">
                                            <ul class="list-unstyled col-md-4">
                                                <li class="hov"><a class="menu" style="display:block" href="@Url.Action("Index", "Products", new { category = "LED Bulbs" })"><span style="font-size:large; margin-left:20px; color: #686868 ; font-weight:bold">LED Bulbs</span></a></li>
                                                <li class="hov"><a class="menu" style="display:block" href="@Url.Action("Index", "Products", new { category = "LED Lamps" })"><span style="font-size:large; margin-left:20px; color: #686868 ; font-weight:bold">LED Lamps</span></a></li>
                                                <li class="divider"></li>
                                                <li class="hov"><a class="menu" style="display:block" href="@Url.Action("Index", "Products", new { category = "Ceiling Lights" })"><span style="font-size:large; margin-left:20px; color: #686868 ; font-weight:bold">Ceiling Lights</span></a></li>
                                                <li class="hov"><a class="menu" style="display:block" href="@Url.Action("Index", "Products", new { category = "LED Panel Lights" })"><span style="font-size:large; margin-left:20px; color: #686868 ; font-weight:bold">LED Panel Lights</span></a></li>
                                            </ul>
                                            <ul class="list-unstyled col-md-4">
                                                <li class="hov"><a class="menu" style="display:block" href="@Url.Action("Index", "Products", new { category = "LED Tube Lights" })"><span style="font-size:large; margin-left:20px; color: #686868 ; font-weight:bold">LED Tube Lights</span></a></li>
                                                <li class="hov"><a class="menu" style="display:block" href="@Url.Action("Index", "Products", new { category = "LED Office Lights" })"><span style="font-size:large; margin-left:20px; color: #686868 ; font-weight:bold">LED Office Lights</span></a></li>
                                                <li class="divider"></li>
                                            </ul>
                                            <ul class="list-unstyled col-md-4">
                                                <li class="hov"><a class="menu" style="display:block" href="@Url.Action("Index", "Products", new { category = "Fancy Lights" })"><span style="font-size:large; margin-left:20px; color: #686868 ; font-weight:bold">Fancy Lights</span></a></li>
                                                <li class="hov"><a class="menu" style="display:block" href="@Url.Action("Index", "Products", new { category = "LED Strip Lights" })"><span style="font-size:large; margin-left:20px; color: #686868 ; font-weight:bold">LED Strip Lights</span></a></li>
                                                <li class="divider"></li>
                                            </ul>
                                        </div>
                                    </li>
                                </ul>
                            </li>
					        <li>
                                <a class="menu" href="" class="dropdown-toggle" data-hover="dropdown" data-toggle="dropdown">Industrial <b class="caret"></b></a>
                                <ul class="dropdown-menu" id="border">
                                    <li><a class="menu" href="@Url.Action("Index", "Products", new { category = "LED Flood Light / Beam Light" })"><span style="font-size:large; font-weight:bold">LED Flood Light / Beam Light</span></a></li>
                                    <li class="divider"></li>
                                    <li><a class="menu" href="@Url.Action("Index", "Products", new { category = "LED HI BAY" })"><span style="font-size:large; font-weight:bold">LED HI BAY</span></a></li>
                                </ul>
                            </li>
					        <li>
                                <a class="menu" href="" class="dropdown-toggle" data-hover="dropdown" data-toggle="dropdown">Outdoor <b class="caret"></b></a>
                                <ul class="dropdown-menu" id="border">
                                    <li><a class="menu" href="@Url.Action("Index", "Products", new { category = "Street Lights" })"><span style="font-size:large; font-weight:bold">Street Lights</span></a></li>
                                </ul>
                            </li>
                            <li><a class="menu @ViewBag.Active3" href="@Url.Action("Index", "Projects")">Our Projects</a></li>
                            <li><a class="menu @ViewBag.Active4" href="@Url.Action("Index", "Catalogue")">Catalogue</a></li>
                            <li><a class="menu @ViewBag.Active5" href="@Url.Action("Index", "Contact")">Contact</a></li>
					      </ul>
					    </div><!-- /navbar-collapse -->
					  </div><!-- / .container-fluid -->
					</nav>
				</div>
			</div>
		</div>
	</header> <!-- end of header area -->
    
    @RenderBody()
    
    <a href="#0" class="cd-top">Top</a>

    <div style="background-color: #1D1D1D;
    background-position: center bottom;
    background-repeat: no-repeat;
    color: #FFFFFF;
    font-size: 20px;
    padding: 35px 0;">
        <div class="container">
            <div class="text-center">
                <p style="font-weight:bold"> Copyright  ©2015<a href="@Url.Action("Index", "Home")"> Allied Renewable Energy</a>. All Rights Reserved.
                <br/>Developed by <a target="_blank" href="mailto:shadmanulislam@gmail.com">Md Shadmanul Islam</a></p>                
            </div>
        </div>
    </div>
	
    

	<!-- script tags
	============================================================= -->
    <script src="~/Content/js/main.js" type="text/javascript"></script>
	<script src="~/Content/js/jquery-2.1.1.js"></script>
	<script src="http://maps.google.com/maps/api/js?sensor=true"></script>
	<script src="~/Content/js/gmaps.js"></script>
	<script src="~/Content/js/smoothscroll.js"></script>
    <script src="~/Content/js/bootstrap-hover-dropdown.min.js" type="text/javascript"></script>
	<script src="~/Content/js/bootstrap.min.js"></script>
	<script src="~/Content/js/custom.js"></script>
</body>
</html>